/* SPDX-FileCopyrightText: 2014-present Kriasoft */
/* SPDX-License-Identifier: MIT */

import { Container, Link, Typography } from "@mui/material";
import { config } from "../../core/config.js";
import { usePageEffect } from "../../core/page.js";
import React from "react";

/**
 * Generated by https://getterms.io
 */
export function Component(): React.JSX.Element {
  usePageEffect({ title: "Privacy Policy" });

  const appName = config.app.name;
  const appOrigin = config.app.origin;
  const email = `hello@${config.app.hostname}`;

  return (
    <Container
      maxWidth="sm"
      sx={{ marginTop: (x) => x.spacing(3), marginBottom: (x) => x.spacing(3) }}
    >
      <Typography variant="h1" gutterBottom>
        About Edge AI
      </Typography>
      <Typography paragraph>
        This project explores the development of an innovative Edge AI solution aimed at bridging the
        technology gap in rural Africa, a region often constrained by language barriers and limited
        internet connectivity. We propose a system that leverages Unstructured Supplementary
        Service Data (USSD) and Interactive Voice Response (IVR) services, allowing users to engage
        with advanced AI technologies using simple mobile devices and their local languages.
      </Typography>
      <Typography paragraph>
        As part of our research preview, we have also designed this simulator for users who are
        unable to utilize the USSD service. This simulator replicates the experience of a basic phone,
        providing an interactive platform for users to familiarize themselves with the USSD interface.
        By offering this research preview, we seek to gather valuable feedback and insights from users
        to refine and improve our Edge AI solution. Through this endeavor, we aim to enable more
        individuals to access and benefit from our AI-driven services, representing a significant
        stride towards utilizing AI for social and economic development in resource-constrained settings
        while ensuring inclusivity and participation in the digital age.
      </Typography>
      <Typography variant="h2" gutterBottom>
        How it works
      </Typography>
      <Typography paragraph>
        If you are familiar with USSD codes and comfortable with using feature phones, this should be a breeze.
      </Typography>
      <ol>
        <li>Click here to navigate to the simulator</li>
        <li>A test phone number will be assigned to you</li>
        <li>Dial the USSD code *920*223#</li>
        <li>Click on the call button and wait for the prompt</li>
        <li>Type any prompt <b>in your local language</b></li>
        <li>Read the disclaimer</li>
        <li>Type N and B to move to next and previous pages respectively</li>
      </ol>
      <Typography variant="h3" gutterBottom>
        Capabilities
      </Typography>
      <ul>
        <li>Will respond in the language of your prompt</li>
        <li>Will decline inappropriate prompts</li>
        <li>Allows you to navigate forward and back through pages of your response</li>
        <li>If network breaks, redialing *920*223# will pick up from where you stopped</li>
      </ul>
      <Typography variant="h3" gutterBottom>
        Limitations
      </Typography>
      <Typography paragraph>
        {appName} is in research preview and still being actively developed and improved. It currently has the following limitations.
      </Typography>
      <ul>
        <li>May display inaccurate or offensive information.</li>
        <li>No support for many African languages yet</li>
        <li>Responses in some languages may be scrambled and/or appear meaningless</li>
      </ul>
      <Typography variant="h3" gutterBottom>
        Legitimate Reasons for Processing Your Personal Information
      </Typography>
      <Typography paragraph>
        We only collect and use your personal information when we have a
        legitimate reason for doing so. In which instance, we only collect
        personal information that is reasonably necessary to provide our
        services to you.
      </Typography>
      <Typography variant="h3" gutterBottom>
        Collection and Use of Information
      </Typography>
      <Typography paragraph>
        We may collect personal information from you when you do any of the
        following on our website:
      </Typography>
      <ul>
        <li>
          Access the {appName} service via the USSD code *920*223#
        </li>
      </ul>
      <Typography paragraph>
        We may collect, hold, use, and disclose information for the following
        purposes, and personal information will not be further processed in a
        manner that is incompatible with these purposes:
      </Typography>
      <ul>
        <li>
          to enable you to customize or personalize your experience of our
          website and USSD service
        </li>
        <li>to contact and communicate with you</li>
        <li>
          for analytics, market research, and business development, including to
          operate and improve our website, associated applications, and
          associated social media platforms
        </li>
        <li>
          to enable you to access and use our website, associated applications,
          and associated social media platforms
        </li>
        <li>for internal record keeping and administrative purposes</li>
      </ul>
      <Typography variant="h3" gutterBottom>
        Security of Your Personal Information
      </Typography>
      <Typography paragraph>
        When we collect and process personal information, and while we retain
        this information, we will protect it within commercially acceptable
        means to prevent loss and theft, as well as unauthorized access,
        disclosure, copying, use, or modification.
      </Typography>
      <Typography paragraph>
        Although we will do our best to protect the personal information you
        provide to us, we advise that no method of electronic transmission or
        storage is 100% secure, and no one can guarantee absolute data security.
        We will comply with laws applicable to us in respect of any data breach.
      </Typography>
      <Typography variant="h3" gutterBottom>
        How Long We Keep Your Personal Information
      </Typography>
      <Typography paragraph>
        We retain your personal information in identifiable form for a maximum of thirty (30) days. Once the need for your personal information has concluded, we will proceed to anonymize it by eliminating all identifying details associated with you.
      </Typography>
      <Typography paragraph>
        However, if necessary, we may retain your personal information in identifiable form for our
        compliance with a legal obligation.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Children’s Privacy
      </Typography>
      <Typography paragraph>
        We do not aim any of our products or services directly at children under
        the age of 13, and we do not knowingly collect personal information
        about children under 13.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Disclosure of Personal Information to Third Parties
      </Typography>
      <Typography paragraph>
        We may disclose personal information to:{" "}
      </Typography>
      <ul>
        <li>a parent, subsidiary, or affiliate of our company</li>
        <li>
          third party service providers for the purpose of enabling them to
          provide their services, for example, AI service providers, IT service providers, data
          storage, hosting and server providers, advertisers, or analytics
          platforms
        </li>
        <li>our employees, contractors, and/or related entities</li>
        <li>our existing or potential agents or business partners</li>
        <li>
          sponsors or promoters of any competition, sweepstakes, or promotion we
          run
        </li>
        <li>
          courts, tribunals, regulatory authorities, and law enforcement
          officers, as required by law, in connection with any actual or
          prospective legal proceedings, or in order to establish, exercise, or
          defend our legal rights
        </li>
        <li>
          third parties, including agents or sub-contractors, who assist us in
          providing information, products, services, or direct marketing to you
          third parties to collect and process data
        </li>
      </ul>
      <Typography variant="h2" gutterBottom>
        International Transfers of Personal Information
      </Typography>
      <Typography paragraph>
        The personal information we collect is stored and/or processed where we
        or our partners, affiliates, and third-party providers maintain
        facilities. Please be aware that the locations to which we store,
        process, or transfer your personal information may not have the same
        data protection laws as the country in which you initially provided the
        information. If we transfer your personal information to third parties
        in other countries: (i) we will perform those transfers in accordance
        with the requirements of applicable law; and (ii) we will protect the
        transferred personal information in accordance with this privacy policy.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Your Rights and Controlling Your Personal Information
      </Typography>
      <Typography paragraph>
        You always retain the right to withhold personal information from us,
        with the understanding that your experience of our website and USSD service may be
        affected. We will not discriminate against you for exercising any of
        your rights over your personal information. If you do provide us with
        personal information you understand that we will collect, hold, use and
        disclose it in accordance with this privacy policy. You retain the right
        to request details of any personal information we hold about you.
      </Typography>
      <Typography paragraph>
        If we receive personal information about you from a third party, we will
        protect it as set out in this privacy policy. If you are a third party
        providing personal information about somebody else, you represent and
        warrant that you have such person’s consent to provide the personal
        information to us.
      </Typography>
      <Typography paragraph>
        If you believe that any information we hold about you is inaccurate, out
        of date, incomplete, irrelevant, or misleading, please contact us using
        the details provided in this privacy policy. We will take reasonable
        steps to correct any information found to be inaccurate, incomplete,
        misleading, or out of date.
      </Typography>
      <Typography paragraph>
        If you believe that we have breached a relevant data protection law and
        wish to make a complaint, please contact us using the details below and
        provide us with full details of the alleged breach. We will promptly
        investigate your complaint and respond to you, in writing, setting out
        the outcome of our investigation and the steps we will take to deal with
        your complaint. You also have the right to contact a regulatory body or
        data protection authority in relation to your complaint.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Use of Cookies
      </Typography>
      <Typography paragraph>
        We use &ldquo;cookies&rdquo; to collect information about you and your
        activity across our site. A cookie is a small piece of data that our
        website stores on your computer, and accesses each time you visit, so we
        can understand how you use our site. This helps us serve you content
        based on preferences you have specified.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Limits of Our Policy
      </Typography>
      <Typography paragraph>
        Our website may link to external sites that are not operated by us.
        Please be aware that we have no control over the content and policies of
        those sites, and cannot accept responsibility or liability for their
        respective privacy practices.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Changes to This Policy
      </Typography>
      <Typography paragraph>
        At our discretion, we may change our privacy policy to reflect updates
        to our business processes, current acceptable practices, or legislative
        or regulatory changes. If we decide to change this privacy policy, we
        will post the changes here at the same link by which you are accessing
        this privacy policy.
      </Typography>
      <Typography paragraph>
        If required by law, we will get your permission or give you the
        opportunity to opt in to or opt out of, as applicable, any new uses of
        your personal information.
      </Typography>
      <Typography variant="h2" gutterBottom>
        Contact Us
      </Typography>
      <Typography paragraph>
        For any questions or concerns regarding your privacy, you may contact us
        using the following details:
      </Typography>
      <Typography paragraph>
        {appName} Support Team (<Link href={`mailto:${email}`}>{email}</Link>)
      </Typography>
    </Container>
  );
}

Component.displayName = "Privacy";
